Added logfile functionality to erasureTests

diff --git a/fileraid/erasureTest b/fileraid/erasureTest
--- a/fileraid/erasureTest
+++ b/fileraid/erasureTest
@@ -56,9 +56,10 @@
 #
 #GNU licenses can be found at http://www.gnu.org/licenses/.
 
-ITER=3 # Number of N+E file arrays to generate
-INITER=3 # Number of error patterns to test for each file array
-POSTSLEEP=2 # Number of seconds the program should sleep after a test
+ITER=20 # Number of N+E file arrays to generate
+INITER=10 # Number of error patterns to test for each file array
+POSTSLEEP=0 # Number of seconds the program should sleep after a test
+LOGFILE=log_errTests.$$ # Name of the test logfile
 
 echo
 echo "Tests of generalized erasure code"
@@ -70,6 +71,9 @@ echo "Generating input file 'testfile.$$' (this will take some time)..."
 dd if=/dev/urandom of=testfile.$$ bs=10M count=20
 echo "done"
 echo
+
+echo "Created testfile.$$" >> $LOGFILE
+echo >> $LOGFILE
 
 cnt=0
 while [[ $cnt -lt $ITER ]]; do
@@ -84,9 +88,12 @@ while [[ $cnt -lt $ITER ]]; do
    bsz=$(( bsz + 10 ))
    echo
    echo "FtoNE : Generating $n+$e striping with at block size of ""$bsz""K..."
+   echo >> $LOGFILE
+   echo "Generating $n+$e striping with bsz $bsz""K..." >> $LOGFILE
    #sleep 1
    ./lanl_ftone testfile.$$ testout.$$ $n $bsz $e > /dev/null 2>&1
    echo "...done"
+   echo "   stripe generation complete" >> $LOGFILE
    #sleep 1
    echo
    ls testout.$$*
@@ -94,15 +101,18 @@ while [[ $cnt -lt $ITER ]]; do
    #sleep 1
 
    echo "Checking the health of the generated files..."
+   echo "Performing health check of initial files..." >> $LOGFILE
    ./lanl_health testout.$$ $n $bsz 209715200 $e > /dev/null 2>&1
    ret=$?
    if [[ $ret -ne 0 ]]; then
       echo -e "\033[0;31mFAIL - faulty health check returned $ret\033[0m"
-      echo "./lanl_health testout.$$ $n $bsz 209715200 $e"
-      ./lanl_health testout.$$ $n $bsz 209715200 $e
-      exit $?
+      echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e"
+      echo "   FAILURE: faulty initial health check" >> $LOGFILE
+      echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e" >> $LOGFILE
+      exit $ret
    fi
    echo "...done.  Health check passed."
+   echo "   health check passed" >> $LOGFILE
    echo
 
    incnt=0
@@ -110,6 +120,8 @@ while [[ $cnt -lt $ITER ]]; do
 
    if [[ $incnt -ne 0 ]]; then
       echo "Continuing with the same $n+$e striping..."
+      echo >> $LOGFILE
+      echo "Continuring to use $n+$e striping with bsz $bsz""K..." >> $LOGFILE
       echo
    fi
 
@@ -135,6 +147,7 @@ while [[ $cnt -lt $ITER ]]; do
    errpos=-1
 
    echo "$nerr error(s) are to be inserted..."
+   echo "Inserting $nerr error(s)..." >> $LOGFILE
    
    {
 
@@ -145,6 +158,7 @@ while [[ $cnt -lt $ITER ]]; do
          done
 
          echo "   placing error at $errpos""..."
+         echo "   placing error at $errpos""..." >> $LOGFILE
 
          efile="testout.$$.$errpos"
 
@@ -152,25 +166,29 @@ while [[ $cnt -lt $ITER ]]; do
             efile="testout.$$.e$(( errpos - n ))"
          fi
          echo "   corrupting file $efile"
+         echo "   corrupting file $efile" >> $LOGFILE
          dd if=/dev/urandom of=$efile bs=1 count=1
 
          ./lanl_health testout.$$ $n $bsz 209715200 $e > /dev/null 2>&1
          ret=$?
          if [[ $ret -eq 0 ]]; then
             echo -e "\033[0;31mFAIL - health check failed to find corruption\033[0m"
-            echo "./lanl_health testout.$$ $n $bsz 209715200 $e"
-            ./lanl_health testout.$$ $n $bsz 209715200 $e
-            exit $?
+            echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e"
+            echo "   FAILURE: health check failed to find corruption" >> $LOGFILE
+            echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e" >> $LOGFILE
+            exit $ret
          fi
          echo "   health check successfully indicated corruption"
+         echo "   health check successfully indicated corruption" >> $LOGFILE
 
          ./lanl_singleHealth $efile $n $bsz 209715200 $e > /dev/null 2>&1
          ret=$?
          if [[ $ret -eq 0 ]]; then
             echo -e "\033[0;31mFAIL - single file health check failed to find corruption\033[0m"
-            echo "./lanl_singleHealth $efile $n $bsz 209715200 $e"
-            ./lanl_singleHealth $efile $n $bsz 209715200 $e
-            exit $?
+            echo "CMD = ./lanl_singleHealth $efile $n $bsz 209715200 $e"
+            echo "   FAILURE: single health failed to find corruption" >> $LOGFILE
+            echo "CMD = ./lanl_singleHealth $efile $n $bsz 209715200 $e" >> $LOGFILE
+            exit $ret
          fi
          echo "   single file health successfully indicated corruption"
 
@@ -190,6 +208,7 @@ while [[ $cnt -lt $ITER ]]; do
             npat="$npat"".1"
          fi #here
          echo "   error insertion successful"
+         echo "   error insertion successful" >> $LOGFILE
          oldpos=$(( oldpos + 1 ))
          
          errcnt=$(( errcnt + 1 ))
@@ -215,75 +234,99 @@ while [[ $cnt -lt $ITER ]]; do
       npat=${npat::-$oldpos}
 
       echo "...errors inserted."
+      echo "Errors inserted, pattern is  $npat   $epat" >> $LOGFILE
       echo
 
       echo "Performing a read of $len from data/erasure files with offset = $offset with N error pattern $npat and E error pattern $epat..."
+      echo "Performing read of $len with offset $offset""..." >> $LOGFILE
       ./lanl_netof testout.$$ $npat $epat $offset $len outfile > /dev/null 2>&1
       echo "...done"
+      echo "...done" >> $LOGFILE
       echo
 
       #sleep 1
       
       echo "Generating a matching file using dd (this may take awhile)..."
+      echo "Generating matching file using dd..." >> $LOGFILE
       #sleep 1
       dd if=testfile.$$ of=cmpout bs=1 count=$len skip=$offset
       echo "...done"
+      echo "...done" >> $LOGFILE
       echo
       echo "Performing comparison..."
+      echo "Performing comparison..." >> $LOGFILE
       #sleep 1
       cmp cmpout outfile
 
       if [[ ! $? -eq 0 ]]; then
          echo -e "\033[0;31mFAIL - output does not match expected data\033[0m"
+         echo "   FAILURE: output of netof does not match the expected data" >> $LOGFILE
          echo "Terminating premeturely..."
-         exit 1
+         exit -1
       fi
       echo "Comparison passed"
+      echo "Comparison passed" >> $LOGFILE
    
       echo "Cleaining up outputs..."
+      echo "Cleaining up outputs..." >> $LOGFILE
       rm outfile cmpout
       echo
 
       echo "Attempting error recovery..."
+      echo "Attempting error recovery..." >> $LOGFILE
       if [[ $npat == *"1"* ]]; then
          echo "   errors exist within N, using \"rebuildne\"..."
+         echo "   errors exist within N, using \"rebuildne\"..." >> $LOGFILE
          ./lanl_rebuildne testout.$$ $npat $epat > /dev/null 2>&1
-         if [[ $? -ne 0 ]]; then
+         ret=$?
+         if [[ $ret -ne 0 ]]; then
             echo -e "\033[0;31mFAIL - rebuild (rebuildne) has failed\033[0m"
-            echo "Rerunning - ./lanl_rebuildne testout.$$ $npat $epat"
+            echo "CMD = ./lanl_rebuildne testout.$$ $npat $epat"
+            echo "   FAILURE: an error occured within rebuildne" >> $LOGFILE
+            echo "CMD = ./lanl_rebuildne testout.$$ $npat $epat" >> $LOGFILE
             ./lanl_rebuildne testout.$$ $npat $epat
-            exit $?
+            exit $ret
          fi
       else
          echo "   no errors exist within N, using \"ntofe\"..."
+         echo "   no errors exist within N, using \"ntofe\"..." >> $LOGFILE
          ./lanl_ntofe testout.$$ cmpfile.$$ $epat > /dev/null 2>&1
-         if [[ $? -ne 0 ]]; then
+         ret=$?
+         if [[ $ret -ne 0 ]]; then
             echo -e "\033[0;31mFAIL - rebuild (ntofe) has failed\033[0m"
-            echo "Rerunning - ./lanl_ntofe testout.$$ cmpfile.$$ $epat"
-            ./lanl_ntofe testout.$$ cmpfile.$$ $epat
-            exit $?
+            echo "CMD = ./lanl_ntofe testout.$$ cmpfile.$$ $epat"
+            echo "   FAILURE: an error occured within ntofe" >> $LOGFILE
+            echo "CMD = ./lanl_ntofe testout.$$ cmpfile.$$ $epat" >> $LOGFILE
+            exit $ret
          fi
          cmp testfile.$$ cmpfile.$$
          ret=$?
          if [[ $ret -ne 0 ]]; then
             echo -e "\033[0;31mFAIL - output file of \"ntofe\" does not match original file\033[0m"
+            echo "   FAILURE: ouput file of ntofe does not match input" >> $LOGFILE
             exit $ret
          fi
          echo "   outfile matches orignal input"
+         echo "   outfile matches orignal input" >> $LOGFILE
          echo "   deleting outfile"
+         echo "   deleting outfile" >> $LOGFILE
          rm cmpfile.$$
       fi
          
       echo "...done"
+      echo "...done" >> $LOGFILE
       
       ./lanl_health testout.$$ $n $bsz 209715200 $e > /dev/null 2>&1
-      if [[ $? -ne 0 ]]; then
+      ret=$?
+      if [[ $ret -ne 0 ]]; then
          echo -e "\033[0;31mFAIL - health check failed after rebuild\033[0m"
-         echo "./lanl_health testout.$$ $n $bsz 209715200 $e"
-         ./lanl_health testout.$$ $n $bsz 209715200 $e
-         exit $?
+         echo "   FAILURE: health check failed after rebuild" >> $LOGFILE
+         echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e"
+         echo "CMD = ./lanl_health testout.$$ $n $bsz 209715200 $e" >> $LOGFILE
+         exit $ret
       fi
       echo "Health check confirms corruption absent"
+      echo "Health check confirms corruption absent" >> $LOGFILE
       echo
 
       #All tests passed for this iteration
@@ -291,6 +334,9 @@ while [[ $cnt -lt $ITER ]]; do
       echo -e "     read of $len at $offset"
       echo -e "     and error pattern   N( $npat )  E( $epat )\033[0m"
 
+      echo "PASS - $n+$e with bsize $bsz""K" >> $LOGFILE 
+      echo "     read of $len at $offset" >> $LOGFILE
+      echo "     and error pattern   N( $npat )  E( $epat )" >> $LOGFILE
    }
 
    sleep $POSTSLEEP
@@ -312,5 +358,7 @@ echo
 
 echo "Cleaning up remaining files..."
 rm testfile.$$ lanl_netof lanl_ftone lanl_rebuildne lanl_health lanl_singleHealth lanl_ntofe
+echo "Removing log file..."
+rm $LOGFILE
 echo "...done"
 
