Added functionality to erasureTest and corrected error in netof

diff --git a/fileraid/erasureTest b/fileraid/erasureTest
--- a/fileraid/erasureTest
+++ b/fileraid/erasureTest
@@ -56,6 +56,7 @@
 #
 #GNU licenses can be found at http://www.gnu.org/licenses/.
 
+ITER=10 # Number of iterations to perform
 
 echo
 echo "Test of generalized erasure code : ftone and netof"
@@ -67,8 +68,141 @@ echo "Generating input file 'testfile'..."
 dd if=/dev/urandom of=testfile bs=10M count=20
 echo "done"
 echo
-echo "FtoNE : Generating stripes and erasure files..."
-./lanl_ftone testfile testout 8 64 3
+
+cnt=0
+while [[ $cnt -lt $ITER ]]; do
+   n=$RANDOM
+   let "n %= 13"
+   n=$(( n + 2 ))
+   e=$RANDOM
+   let "e %= 3"
+   e=$(( e + 1 ))
+   bsz=$RANDOM
+   let "bsz %= 90"
+   bsz=$(( bsz + 10 ))
+   echo
+   echo "FtoNE : Generating $n+$e striping with at block size of ""$bsz""K..."
+   #sleep 1
+   ./lanl_ftone testfile testout $n $bsz $e > /dev/null 2>&1
+   echo "...done"
+   #sleep 1
+   echo
+   ls testout*
+   echo
+   #sleep 1
+
+   bsz=$RANDOM
+   let "bsz %= 1024"
+   offset=$RANDOM
+   offset=$(( offset * bsz ))
+   let "offset %= 20470"
+   bsz=$RANDOM
+   let "bsz %= 1024"
+   len=$RANDOM
+   len=$(( len * bsz ))
+   bsz=$(( 20480 - offset ))
+   let "len %= $bsz"
+
+   bsz=$RANDOM
+   let "bsz %= $e"
+   bsz=$(( bsz + 1 ))
+   npat=""
+   maxpos=$(( n + e - bsz ))
+   oldpos=0
+   errcnt=0
+   errpos=-1
+   
+   {
+
+      while [[ $errcnt -lt $bsz ]]; do
+         while [[ $errpos -lt $oldpos ]]; do
+            errpos=$RANDOM
+            let "errpos %= maxpos"
+         done
+
+         echo "Placing error at $errpos"
+
+         while [[ $oldpos -lt $errpos ]]; do
+            if [[ $npat == "" ]]; then
+               npat="0"
+            else
+               npat="$npat"".0"
+            fi
+            oldpos=$(( oldpos + 1 ))
+         done
+
+         if [[ $npat == "" ]]; then
+            npat="1"
+         else
+            npat="$npat"".1"
+         fi
+         echo "   Error placed"
+         oldpos=$(( oldpos + 1 ))
+         
+         errcnt=$(( errcnt + 1 ))
+         maxpos=$(( maxpos + 1 ))
+      done
+
+      maxpos=$(( maxpos ))
+
+      while [[ $oldpos -lt $maxpos ]]; do
+         if [[ $npat == "" ]]; then
+            npat="0"
+         else
+            npat="$npat"".0"
+         fi
+         oldpos=$(( oldpos + 1 ))
+      done
+
+
+      oldpos=$(( n * 2 ))
+
+      epat=${npat:$oldpos}
+      oldpos=$(( e * 2 ))
+      npat=${npat::-$oldpos}
+
+      echo "Performing a read of $len from data/erasure files with offset = $offset with N error pattern $npat and E error pattern $epat..."
+      ./lanl_netof testout $npat $epat $offset $len outfile > /dev/null 2>&1
+
+      echo "...done"
+      echo
+   }
+
+
+   #sleep 1
+   
+   echo "Generating a matching file usind dd..."
+   #sleep 1
+   dd if=testfile of=cmpout bs=1 count=$len skip=$offset
+   echo "...done"
+   echo
+   echo "Performing comparison..."
+   #sleep 1
+   cmp cmpout outfile
+
+   if [[ ! $? -eq 0 ]]; then
+      echo -e "\033[0;31mFAIL\033[0m"
+      echo "Terminating premeturely..."
+      exit 1
+   else
+      echo -e "\033[0;32mPASS\033[0m"
+   fi
+
+   sleep 2
+   
+   echo "Cleaining up outputs..."
+   rm testout.*
+   rm outfile cmpout
+
+   cnt=$(( cnt + 1 ))
+done
+
+#./lanl_ftone testfile testout 8 64 3
+echo "done"
+echo
+
+
+
 
 echo "Cleaning up..."
 
