Enabled the erasureTest script to perform corruption of meta files in addition to data/erasure

diff --git a/erasureLib/erasureTest b/erasureLib/erasureTest
--- a/erasureLib/erasureTest
+++ b/erasureLib/erasureTest
@@ -70,6 +70,8 @@ FSZ=20  # Size of the input file in 10s of MBytes (i.e. a value of 20 -> 200M fi
 
 re='^[0-9]+$'
 
+
+
 if [[ $# -gt 0 ]]; then
    if [[ $1 =~ $re ]]; then
       ITER=$1
@@ -109,6 +111,86 @@ if [[ ! -e libneTest ]]; then
    exit 1
 fi
 
+
+# corruption insertion function
+corrupt_file() {
+   ftocorr="$1"
+   echo "   Corrupting file \"$ftocorr\"..."
+   echo "      creating backup of $ftocorr"
+   cp $ftocorr "$ftocorr".backup
+
+   ctype=$(( RANDOM % (3-ICRC) ))
+   if [[ $ctype -eq 0 ]]; then
+      echo "      corrupting file $ftocorr ( corruption-type : removal )"
+      echo "      corrupting file $ftocorr ( corruption-type : removal )" >> $LOGFILE
+      rm $ftocorr
+   elif [[ $ctype -eq 1 ]]; then
+      echo "      corrupting file $ftocorr ( corruption-type : truncate )"
+      echo "      corrupting file $ftocorr ( corruption-type : truncate )" >> $LOGFILE
+      fsize=$( stat $stfmt $ftocorr )
+      corr=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % fsize ))
+      if [[ $(( fsize - corr )) -lt 2  &&  "$ftocorr" =~ .meta ]]; then
+         corr=$(( corr - 1 )) # meta files aren't affected by the loss of only the last byte
+      fi
+      echo "      truncating from $fsize to $corr bytes"
+      echo "      truncating from $fsize to $corr bytes" >> $LOGFILE
+      truncate -s $corr $ftocorr
+      echo "      creating backup of corrupted file"
+      cp $ftocorr "$ftocorr".corrupted
+   else
+      echo "      corrupting file $ftocorr ( corruption-type : silent )"
+      echo "      corrupting file $ftocorr ( corruption-type : silent )" >> $LOGFILE
+      fsize=$( stat $stfmt $ftocorr )
+      corr=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % fsize ))
+      if [[ $corr -eq 0 ]]; then corr=1; fi # make sure we are actually inserting an error
+      offset=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % ( fsize + 1 - corr ) ))
+      if [[ $corr -eq 1  &&  $offset -eq $(( fsize - 1 ))  &&  "$ftocorr" =~ .meta ]]; then
+         offset=$(( offset - 1 )) # meta files aren't affected by the loss of only the last byte
+      fi
+      echo "      inserting $corr random bytes at offset $offset"
+      echo "      inserting $corr random bytes at offset $offset" >> $LOGFILE
+
+      corrmegab=$(( ($corr / 1048576) + 1 ))
+      dd if=/dev/urandom of="$ftocorr".esource bs=1M count=1 > /dev/null 2>&1
+
+      cp $ftocorr $ftocorr".tmp"
+      diff=0
+      while [[ $diff -eq 0 ]]; do
+         corr_done=$(( 1048576 - (offset % 1048576) ))
+         if [[ $corr_done -gt $corr ]]; then corr_done=$corr; fi
+         # insert enough to align our offset to megabyte boundaries
+         dd if="$ftocorr".esource of=$ftocorr bs=1c count=$corr_done seek=$offset conv=notrunc > /dev/null 2>&1
+         while [[ $corr_done -lt $corr ]]; do
+            tocorr=1
+            corrbs="1M"
+            toffset=$(( (offset + corr_done) / 1048576 ))
+            if [[ $(( $corr_done + 1048576 )) -gt $corr ]]; then
+               tocorr=$(( corr - corr_done ))
+               corrbs="1c"
+               toffset=$(( offset + corr_done ))
+            fi
+            dd if="$ftocorr".esource of=$ftocorr bs=$corrbs count=$tocorr seek=$toffset conv=notrunc > /dev/null 2>&1
+            corr_done=$(( corr_done + 1048576 ))
+         done
+         diff $ftocorr $ftocorr".tmp" > /dev/null 2>&1
+         diff=$?
+         if [[ $diff -eq 0 ]]; then
+            echo "      corrption insertion did not alter file, retrying"
+         fi
+      done
+      rm $ftocorr".tmp"
+      rm "$ftocorr".esource
+      echo "      creating backup of corrupted file"
+      cp $ftocorr "$ftocorr".corrupted
+   fi
+
+   echo "   file corruption complete"
+
+   return $ctype
+
+}
+
+
 re=".* Active.*"
 
 ret=$( ./libneTest crc-status | tail -n 2 )
@@ -145,7 +227,7 @@ if [[ ! -e $WORK_DIRECTORY ]]; then
    echo "done"
 fi
 
-echo "Generating input file '$DATAFILE' (this will take some time)..."
+echo "Generating input file '$DATAFILE'..."
 dd if=/dev/urandom of=$DATAFILE bs=10485760 count=$FSZ
 echo "done"
 echo
@@ -166,20 +248,16 @@ while [[ $cnt -lt $ITER ]]; do
    start=$RANDOM
    let "start %= $(( n + e ))"
 
-   err_free=0
+   met_err_free=0
+   dat_err_free=0
 
    echo
    echo "Generating $n+$e striping starting at file $start..."
    echo >> $LOGFILE
    echo >> $LIBTLOG
    echo "Generating $n+$e striping starting at file $start""..." >> $LOGFILE
-#   tcnt=$( date +%s%N )
    { ret=$( time -p ./libneTest write -r $EPAT $n $e $start -s $FSZ -i $DATAFILE 2>&1 | tee -a $LIBTLOG | tail -n 1 | awk '{print $NF}' ); } 2>> $TLOGPREF$$.write
 
-#   tcnt="`date +%s%N` - $tcnt"
-#   if [[ $BC -eq 0 ]]; then
-#      tcnt=$( echo "$tcnt" | bc )
-#   fi
 
    if [[ ! $ret =~ $re  ||  $ret -ne 0 ]]; then
       echo -e "\033[0;31mFAIL - write operation returned an unexpected status"
@@ -188,9 +266,7 @@ while [[ $cnt -lt $ITER ]]; do
       echo "CMD = ./libneTest write -r $EPAT $n $e $start -s $FSZ -i $DATAFILE" >> $LOGFILE
       exit -1
    fi
-#   echo "...done.  Elapsed time = $tcnt""."
    echo "   stripe generation complete" >> $LOGFILE
-#   echo "$tcnt" >> $TLOGPREF$$.write
    echo
    ls $( echo "$EPAT" | sed 's/%d/\*/' )
    echo
@@ -206,178 +282,124 @@ while [[ $cnt -lt $ITER ]]; do
          echo
       fi
 
+      met_err_list=( 0 )
+      dat_err_list=( 0 )
+      silent_err_list=( 0 )
+
+      stat=0
+      tstat=0
+
+      # Insert Meta Corruption
       nerr=$RANDOM
       let "nerr %= $(( e + 1 ))"
-
       if [[ $nerr -eq 0 ]]; then
-         if [[ $err_free -eq 1 ]]; then
+         if [[ $met_err_free -eq 1 ]]; then
             nerr=$e
          fi
-         err_free=1
+         met_err_free=1
+      elif [[ $nerr -eq $(( n + e - 1 )) ]]; then
+         # special case, we can't leave only a single valid meta file, as there is no guaratee we will get correct values then
+         nerr=$(( nerr - 1 ))
       fi
+      errcnt=0
+
+      echo "$nerr meta error(s) are to be inserted..."
+      echo "Inserting $nerr meta error(s)..." >> $LOGFILE
+
+      while [[ $errcnt -lt $nerr ]]; do
+         errpos=$RANDOM
+         let "errpos %= $(( n + e ))"
+         if [[ ${met_err_list[$errpos]} -eq 0 ]]; then
+            # only corrupt the file if we are hitting a new postion
+            errcnt=$(( errcnt + 1 ))
+            met_err_list[$errpos]=1
+            stat=$(( stat + 2**errpos ))
+            tstat=$(( tstat + 2**errpos ))
+            corrupt_file "$( echo "$EPAT" | sed 's/%d/'"$errpos"'/' | sed 's/$/.meta/' )"
+         fi
+      done
 
       npat=""
-      maxpos=$(( n + e - nerr + 1 ))
-      oldpos=0
+      for pos in $(seq 0 $(( n + e - 1 )) ); do
+         if [[ ${met_err_list[$pos]} -eq 0  ]]; then
+            npat="$npat""0 "
+         else
+            npat="$npat""1 "
+         fi
+      done
+
+      echo "Meta error insertion complete, pattern is : $npat"
+      echo "Meta errors inserted, pattern is  $npat" >> $LOGFILE
+
+ 
+      # Insert Data Corruption
+      nerr=$RANDOM
+      let "nerr %= $(( e + 1 ))"
+      if [[ $nerr -eq 0 ]]; then
+         if [[ $dat_err_free -eq 1 ]]; then
+            nerr=$e
+         fi
+         dat_err_free=1
+      fi
       errcnt=0
-      errpos=-1
-      readerr=0 # read may not detect all errors
-      silent_count=0
 
-      echo "$nerr error(s) are to be inserted..."
-      echo "Inserting $nerr error(s)..." >> $LOGFILE
-      
-      {
+      echo "$nerr data error(s) are to be inserted..."
+      echo "Inserting $nerr data error(s)..." >> $LOGFILE
 
-         stat=0
-
-         while [[ $errcnt -lt $nerr ]]; do
-            while [[ $errpos -lt $oldpos ]]; do
-               errpos=$RANDOM
-               let "errpos %= maxpos"
-            done
-
-            echo "   placing error at $errpos""..."
-            echo "   placing error at $errpos""..." >> $LOGFILE
-            stat=$(( stat + 2**errpos ))
-
-            efile=$( echo "$EPAT" | sed 's/%d/'"$errpos"'/' )
-
-            echo "      creating backup of $efile""..."
-            cp $efile "$efile".backup
-
+      while [[ $errcnt -lt $nerr ]]; do
+         errpos=$RANDOM
+         let "errpos %= $(( n + e ))"
+         if [[ ${dat_err_list[$errpos]} -eq 0 ]]; then
+            # only corrupt the file if we are hitting a new postion
             truepos=$(( errpos - start ))
             if [[ $truepos -lt 0 ]]; then
                truepos=$(( truepos + n + e ))
             fi
-               
-            #if [[ $truepos -lt $n ]]; then
-            #   readerr=1
-            #fi
-
-            ctype=$(( RANDOM % (3-ICRC) ))
-            if [[ $ctype -eq 0 ]]; then
-               echo "      corrupting file $efile ( corruption-type : removal )"
-               echo "      corrupting file $efile ( corruption-type : removal )" >> $LOGFILE
-               rm $efile
-            elif [[ $ctype -eq 1 ]]; then
-               err_list[$silent_count]=$errpos
-               silent_count=$(( silent_count + 1 ))
-               echo "      corrupting file $efile ( corruption-type : truncate )"
-               echo "      corrupting file $efile ( corruption-type : truncate )" >> $LOGFILE
-               fsize=$( stat $stfmt $efile )
-               corr=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % fsize ))
-               echo "      truncating from $fsize to $corr bytes"
-               echo "      truncating from $fsize to $corr bytes" >> $LOGFILE
-               #dd if=$efile of=$efile.tmp bs=1 count=$corr > /dev/null 2>&1
-               #rm $efile
-               #mv $efile.tmp $efile
-               truncate -s $corr $efile
-               echo "      creating backup of corrupted file"
-               cp $efile "$efile".corrupted
-            else
-               err_list[$silent_count]=$errpos
-               silent_count=$(( silent_count + 1 ))
-               echo "      corrupting file $efile ( corruption-type : silent )"
-               echo "      corrupting file $efile ( corruption-type : silent )" >> $LOGFILE
-               fsize=$( stat $stfmt $efile )
-               corr=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % fsize ))
-               offset=$(( `od -N 4 -t uL -An /dev/urandom | awk '{print $1}'` % ( fsize - corr ) ))
-               echo "      inserting $corr random bytes at offset $offset"
-               echo "      inserting $corr random bytes at offset $offset" >> $LOGFILE
-
-               corrmegab=$(( ($corr / 1048576) + 1 ))
-               dd if=/dev/urandom of="$efile".esource bs=1M count=1 > /dev/null 2>&1
-
-               cp $efile $efile".tmp"
-               diff=0
-               while [[ $diff -eq 0 ]]; do
-                  corr_done=$(( 1048576 - (offset % 1048576) ))
-                  if [[ $corr_done -gt $corr ]]; then corr_done=$corr; fi
-                  # insert enough to align our offset to megabyte boundaries
-                  dd if="$efile".esource of=$efile bs=1c count=$corr_done seek=$offset conv=notrunc > /dev/null 2>&1
-                  while [[ $corr_done -lt $corr ]]; do
-                     tocorr=1
-                     corrbs="1M"
-                     toffset=$(( (offset + corr_done) / 1048576 ))
-                     if [[ $(( $corr_done + 1048576 )) -gt $corr ]]; then
-                        tocorr=$(( corr - corr_done ))
-                        corrbs="1c"
-                        toffset=$(( offset + corr_done ))
-                     fi
-                     dd if="$efile".esource of=$efile bs=$corrbs count=$tocorr seek=$toffset conv=notrunc > /dev/null 2>&1
-                     corr_done=$(( corr_done + 1048576 ))
-                  done
-                  diff $efile $efile".tmp" > /dev/null 2>&1
-                  diff=$?
-                  if [[ $diff -eq 0 ]]; then
-                     echo "      corrption insertion did not alter file, retrying"
-                  fi
-               done
-               rm $efile".tmp"
-               rm "$efile".esource
-               echo "      creating backup of corrupted file"
-               cp $efile "$efile".corrupted
-            fi
-
-            while [[ $oldpos -lt $errpos ]]; do
-               if [[ $npat == "" ]]; then
-                  npat="0"
-               else
-                  npat="$npat"".0"
-               fi
-               oldpos=$(( oldpos + 1 ))
-            done
-
-            if [[ $npat == "" ]]; then
-               npat="1"
-            else
-               npat="$npat"".1"
-            fi
-            echo "      error creation successful"
-            echo "      error creation successful" >> $LOGFILE
-            oldpos=$(( oldpos + 1 ))
-            
             errcnt=$(( errcnt + 1 ))
-            maxpos=$(( maxpos + 1 ))
-         done
-
-         maxpos=$(( maxpos - 1 ))
-
-         while [[ $oldpos -lt $maxpos ]]; do
-            if [[ $npat == "" ]]; then
-               npat="0"
-            else
-               npat="$npat"".0"
+            dat_err_list[$errpos]=1
+            # if there are no previous errors at this postion, note it for rc checking
+            if [[ ${met_err_list[$errpos]} -eq 0 ]]; then
+               stat=$(( stat + 2**errpos ))
             fi
-            oldpos=$(( oldpos + 1 ))
-         done
-
-         echo "Error insertion complete, pattern is : $npat"
-         echo "Errors inserted, pattern is  $npat" >> $LOGFILE
-         echo "There are $silent_count potentially silent errors in the stripe"
-         echo "There are $silent_count potentially silent errors in the stripe" >> $LOGFILE
-
-         tstat=$stat
-         tmp=0
-         while [[ $readerr -eq 0  &&  $tmp -lt $silent_count ]]; do
-            errpos=${err_list[$tmp]}
-            truepos=$(( errpos - start ))
-            if [[ $truepos -lt 0 ]]; then
-               truepos=$(( truepos + n + e ))
+            corrupt_file "$( echo "$EPAT" | sed 's/%d/'"$errpos"'/' )"
+            # only note errors which do not align with meta errors and which are removal type or in data blocks
+            if [[ ${met_err_list[$errpos]} -eq 0  &&  ( $? -eq 0  ||  $truepos -lt $n ) ]]; then
+               tstat=$(( tstat + 2**errpos ))
             fi
+         fi
+      done
 
-            if [[ ! $truepos -lt $n ]]; then
-               tstat=$(( tstat - (2**errpos) ))
-            fi
+      npat=""
+      for pos in $(seq 0 $(( n + e - 1 )) ); do
+         if [[ ${dat_err_list[$pos]} -eq 0 ]]; then
+            npat="$npat""0 "
+         else
+            npat="$npat""1 "
+         fi
+      done
 
-            tmp=$(( tmp + 1 ))
-         done
+      echo "Data error insertion complete, pattern is : $npat"
+      echo "Data errors inserted, pattern is  $npat" >> $LOGFILE
 
-         echo "The minimum acceptible error detection for reads is $tstat"
-         echo "The minimum acceptible error detection for reads is $tstat" >> $LOGFILE
-         echo
-         echo >> $LIBTLOG
+
+      echo "The minimum acceptible error detection for reads is $tstat"
+      echo "The minimum acceptible error detection for reads is $tstat" >> $LOGFILE
+      echo
+      echo >> $LIBTLOG
+
+      # finally, get the total error pattern
+      npat=""
+      for pos in $(seq 0 $(( n + e - 1 )) ); do
+         if [[ ${met_err_list[$pos]} -eq 0  &&  ${dat_err_list[$pos]} -eq 0 ]]; then
+            npat="$npat""0 "
+         else
+            npat="$npat""1 "
+         fi
+      done
+
+
+
+      {
 
          echo -n "Verifying corruption pattern (expecting pattern $stat)..."
          echo "Verifying corruption pattern (expecting pattern $stat)..." >> $LOGFILE
