Improved error reporting of erasureTest

diff --git a/erasureLib/erasureTest b/erasureLib/erasureTest
--- a/erasureLib/erasureTest
+++ b/erasureLib/erasureTest
@@ -89,11 +89,18 @@ while [[ $cnt -lt $ITER ]]; do
    start=$RANDOM
    let "start %= $(( n + e ))"
    echo
-   echo "FtoNE : Generating $n+$e striping starting at file $start..."
+   echo "Generating $n+$e striping starting at file $start..."
    echo >> $LOGFILE
-   echo "Generating $n+$e striping starting at file $start..." >> $LOGFILE
+   echo "Generating $n+$e striping starting at file $start""..." >> $LOGFILE
    #sleep 1
-   ./libTest write testfile.$$ testout.%d.$$ $n $e $start #> /dev/null 2>&1
+   ./libTest write testfile.$$ testout.%d.$$ $n $e $start > /dev/null 2>&1
+   if [[ ! $? -eq 0 ]]; then
+      echo -e "\033[0;31mFAIL - write operation returned a non-zero status"
+      echo -e "CMD = ./libTest write testfile.$$ testout.%d.$$ $n $e $start\033[0m"
+      echo "   FAILURE: wite operation returned a non-sero status" >> $LOGFILE
+      echo "CMD = ./libTest write testfile.$$ testout.%d.$$ $n $e $start" >> $LOGFILE
+      exit -1
+   fi
    echo "...done"
    echo "   stripe generation complete" >> $LOGFILE
    #sleep 1
@@ -185,12 +192,24 @@ while [[ $cnt -lt $ITER ]]; do
       done
 
       echo "...errors inserted."
+      echo "Errors pattern is  $npat"
       echo "Errors inserted, pattern is  $npat" >> $LOGFILE
       echo
 
-      echo "Performing a read of $len from data/erasure files with offset = $offset with error pattern $npat..."
-      echo "Performing read of $len""..." >> $LOGFILE
-      ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200 #> /dev/null 2>&1
+      echo "Performing a read of all data from data/erasure files..."
+      echo "Performing read of all data from striping..." >> $LOGFILE
+      ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200 > /dev/null 2>&1
+      if [[ ! $? -eq 0 ]]; then
+         echo -e "\033[0;31mFAIL - read operation returned a non-zero status"
+         echo -e "CMD = ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200\033[0m"
+         echo "   FAILURE: read operation returned a non-sero status" >> $LOGFILE
+         echo "CMD = ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200" >> $LOGFILE
+         exit -1
+      fi
+      echo "...done"
+      echo "   stripe generation complete" >> $LOGFILE
+      #sleep 1
+      echo
       echo "...done.  Output file is \"outfile.$$\""
       echo "...done.  Output file is \"outfile.$$\"" >> $LOGFILE
       echo
@@ -274,11 +293,10 @@ while [[ $cnt -lt $ITER ]]; do
 #      echo
 
       #All tests passed for this iteration
-      echo -e "\033[0;32mPASS - $n+$e with bsize $bsz""K"
-      echo -e "     read of $len at $offset"
-      echo -e "     and error pattern   N( $npat )  E( $epat )\033[0m"
+      echo -e "\033[0;32mPASS - $n+$e with start position $start"
+      echo -e "     and error pattern   $npat\033[0m"
 
-      echo "PASS - $n+$e with start file $start" >> $LOGFILE 
+      echo "PASS - $n+$e with start position $start" >> $LOGFILE 
       echo "     and error pattern   $npat" >> $LOGFILE
    }
 
