Corrections throughout to improver MAC compatability

diff --git a/erasureLib/erasureTest b/erasureLib/erasureTest
--- a/erasureLib/erasureTest
+++ b/erasureLib/erasureTest
@@ -69,12 +69,26 @@ echo
 echo "Tests erasure library functions..."
 echo
 
+stfmt="-c%s"
+
+{ stat $stfmt 2>&1; } > /dev/null
+ret=$?
+if [[ $ret -ne 0 ]]; then
+   stfmt="-f %z"
+   { stat $stfmt 2>&1; } > /dev/null
+   ret=$?
+   if [[ $ret -ne 0 ]]; then
+      echo "Failed to identify proper 'stat' argument format!"
+      exit -1
+   fi
+fi
+
 if [[ ! -e libTest ]]; then
    echo "erasureTest: error: could not locate executable \"libTest\", please run this script from within the \"erasureLib\" directory!"
    exit 1
 fi
 
-./libTest crc-status
+./libTest crc-status > /dev/null
 ICRC=$?
 if [[ $ICRC -eq 0 ]]; then
    echo "INTERMEDIATE CRCS - ACTIVE"
@@ -115,14 +129,13 @@ while [[ $cnt -lt $ITER ]]; do
    echo >> $LOGFILE
    echo >> $LIBTLOG
    echo "Generating $n+$e striping starting at file $start""..." >> $LOGFILE
-   tcnt=$( date +%s%N )
+#   tcnt=$( date +%s%N )
+   { ret=$( time -p ./libTest write testfile.$$ testout.%d.$$ $n $e $start 209715200 2>&1 | tee -a $LIBTLOG | tail -n 1 ); } 2> $TLOGPREF$$.write
 
-   ret=$( ./libTest write testfile.$$ testout.%d.$$ $n $e $start 209715200 2>&1 | tee -a $LIBTLOG | tail -n 1 )
-
-   tcnt="`date +%s%N` - $tcnt"
-   if [[ $BC -eq 0 ]]; then
-      tcnt=$( echo "$tcnt" | bc )
-   fi
+#   tcnt="`date +%s%N` - $tcnt"
+#   if [[ $BC -eq 0 ]]; then
+#      tcnt=$( echo "$tcnt" | bc )
+#   fi
 
    if [[ ! $ret =~ $re  ||  $ret -ne 0 ]]; then
       echo -e "\033[0;31mFAIL - write operation returned an unexpected status"
@@ -131,9 +144,9 @@ while [[ $cnt -lt $ITER ]]; do
       echo "CMD = ./libTest write testfile.$$ testout.%d.$$ $n $e $start 209715200" >> $LOGFILE
       exit -1
    fi
-   echo "...done.  Elapsed time = $tcnt""."
+#   echo "...done.  Elapsed time = $tcnt""."
    echo "   stripe generation complete" >> $LOGFILE
-   echo "$tcnt" >> $TLOGPREF$$.write
+#   echo "$tcnt" >> $TLOGPREF$$.write
    echo
    ls testout.*.$$
    echo
@@ -203,16 +216,18 @@ while [[ $cnt -lt $ITER ]]; do
             silent_count=$(( silent_count + 1 ))
             echo "   corrupting file $efile ( corruption-type : truncate )"
             echo "   corrupting file $efile ( corruption-type : truncate )" >> $LOGFILE
-            fsize=$( stat -c%s $efile )
+            fsize=$( stat $stfmt $efile )
             corr=$(( RANDOM % fsize ))
             echo "      truncating from $fsize to $corr bytes"
-            truncate -s $corr $efile
+            dd if=$efile of=$efile.tmp bs=1 count=$corr > /dev/null 2>&1
+            rm $efile
+            mv $efile.tmp $efile
          else
             err_list[$silent_count]=$errpos
             silent_count=$(( silent_count + 1 ))
             echo "   corrupting file $efile ( corruption-type : silent )"
             echo "   corrupting file $efile ( corruption-type : silent )" >> $LOGFILE
-            fsize=$( stat -c%s $efile )
+            fsize=$( stat $stfmt $efile )
             corr=$(( RANDOM % fsize ))
             offset=$(( RANDOM % ( fsize - corr ) ))
             echo "      inserting $corr random bytes at offset $offset"
@@ -244,7 +259,7 @@ while [[ $cnt -lt $ITER ]]; do
             npat="1"
          else
             npat="$npat"".1"
-         fi #here
+         fi
          echo "   error creation successful"
          echo "   error creation successful" >> $LOGFILE
          oldpos=$(( oldpos + 1 ))
@@ -288,14 +303,14 @@ while [[ $cnt -lt $ITER ]]; do
       echo >> $LIBTLOG
       echo "Performing a read of all data from striping (expected return value = $tstat)..."
       echo "Performing read of all data from striping (expected return value = $tstat)..." >> $LOGFILE
-      tcnt=$( date +%s%N )
+#      tcnt=$( date +%s%N )
       
-      ret=$( ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200 2>&1 | tee -a $LIBTLOG | tail -n 1 )
+      { ret=$( time -p ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200 2>&1 | tee -a $LIBTLOG | tail -n 1 ); } 2> $TLOGPREF$$.read
       
-      tcnt="`date +%s%N` - $tcnt"
-      if [[ $BC -eq 0 ]]; then
-         tcnt=$( echo "$tcnt" | bc )
-      fi
+#      tcnt="`date +%s%N` - $tcnt"
+#      if [[ $BC -eq 0 ]]; then
+#         tcnt=$( echo "$tcnt" | bc )
+#      fi
 
       if [[ ! $ret =~ $re  ||  $ret -ne $tstat ]]; then
          echo -e "\033[0;31mFAIL - read operation returned an inappropriate status, expected $tstat but recieved $ret"
@@ -304,16 +319,13 @@ while [[ $cnt -lt $ITER ]]; do
          echo "CMD = ./libTest read outfile.$$ testout.%d.$$ $n $e $start 209715200" >> $LOGFILE
          exit -1
       fi
-      echo "...done.  Elapsed time = $tcnt"". Output file is \"outfile.$$\""
-      echo "...done.  Elapsed time = $tcnt"". Output file is \"outfile.$$\"" >> $LOGFILE
-      echo "$tcnt" >> $TLOGPREF$$.read
+#      echo "...done.  Elapsed time = $tcnt"". Output file is \"outfile.$$\""
+#      echo "...done.  Elapsed time = $tcnt"". Output file is \"outfile.$$\"" >> $LOGFILE
+#      echo "$tcnt" >> $TLOGPREF$$.read
       echo
-
-      #sleep 1
       
       echo "Performing comparison..."
       echo "Performing comparison..." >> $LOGFILE
-      #sleep 1
       cmp testfile.$$ outfile.$$
 
       if [[ $? -ne 0 ]]; then
@@ -337,14 +349,14 @@ while [[ $cnt -lt $ITER ]]; do
          echo >> $LIBTLOG
          echo "Attempting error recovery..."
          echo "Attempting error recovery..." >> $LOGFILE
-         tcnt=$( date +%s%N )
+#         tcnt=$( date +%s%N )
          
-         ret=$( ./libTest rebuild testout.%d.$$ $n $e $start 2>&1 | tee -a $LIBTLOG | tail -n 1 )
+         { ret=$( time -p ./libTest rebuild testout.%d.$$ $n $e $start 2>&1 | tee -a $LIBTLOG | tail -n 1 ); } 2>$TLOGPREF$$.recovery
 
-         tcnt="`date +%s%N` - $tcnt"
-         if [[ $BC -eq 0 ]]; then
-            tcnt=$( echo "$tcnt" | bc )
-         fi
+#         tcnt="`date +%s%N` - $tcnt"
+#         if [[ $BC -eq 0 ]]; then
+#            tcnt=$( echo "$tcnt" | bc )
+#         fi
 
          if [[ ! $ret =~ $re  ||  $ret -ne $stat ]]; then
             echo -e "\033[0;31mFAIL - ne_rebuild has failed, expected return of $stat but recieved $ret"
@@ -354,21 +366,21 @@ while [[ $cnt -lt $ITER ]]; do
             exit $ret
          fi
 #         ./libTest write testfile.$$ testout.%d.$$ $n $e $start 209715200 > /dev/null 2>&1
-         echo "...recovery complete.  Elapsed time = $tcnt""."
-         echo "...recovery complete.  Elapsed time = $tcnt""." >> $LOGFILE
-         echo "$tcnt" >> $TLOGPREF$$.recovery
+#         echo "...recovery complete.  Elapsed time = $tcnt""."
+#         echo "...recovery complete.  Elapsed time = $tcnt""." >> $LOGFILE
+#         echo "$tcnt" >> $TLOGPREF$$.recovery
       fi
 
       echo "Checking the striping for corruption..."
       echo "Checking the striping for corruption..." >> $LOGFILE
-      tcnt=$( date +%s%N )
+#      tcnt=$( date +%s%N )
 
-      ret=$( ./libTest status testout.%d.$$ $n $e $start 2>&1 | tail -n 1 )
+      { ret=$( time -p ./libTest status testout.%d.$$ $n $e $start 2>&1 | tail -n 1 ); } 2>$TLOGPREF$$.status
 
-      tcnt="`date +%s%N` - $tcnt"
-      if [[ $BC -eq 0 ]]; then
-         tcnt=$( echo "$tcnt" | bc )
-      fi
+#      tcnt="`date +%s%N` - $tcnt"
+#      if [[ $BC -eq 0 ]]; then
+#         tcnt=$( echo "$tcnt" | bc )
+#      fi
 
       if [[ ! $ret =~ $re  ||  $ret -ne 0 ]]; then
          echo -e "\033[0;31mFAIL - status check indicates corruption present in erasure striping"
@@ -377,9 +389,9 @@ while [[ $cnt -lt $ITER ]]; do
          echo "CMD = ./libTest status testout.%d.$$ $n $e $start" >> $LOGFILE
          exit $ret
       fi
-      echo "...no corruption found.  Elapsed time = $tcnt""."
-      echo "...no corruption found.  Elapsed time = $tcnt""." >> $LOGFILE
-      echo "$tcnt" >> $TLOGPREF$$.status
+#      echo "...no corruption found.  Elapsed time = $tcnt""."
+#      echo "...no corruption found.  Elapsed time = $tcnt""." >> $LOGFILE
+#      echo "$tcnt" >> $TLOGPREF$$.status
       echo
 
       #All tests passed for this iteration
@@ -416,44 +428,66 @@ if [[ $BC -eq 0 ]]; then
    count=0
 
    while read -r line; do
+      line=$( echo "$line" | awk '{print $2}' )
       tcnt="$tcnt + $line"
       count=$(( count + 1 ));
    done < "$TLOGPREF$$.write"
-   tcnt=$( echo "$tcnt ) / $count" | bc )
-   
-   output="$output\nWrites:,Performed = $count,AvgTime = $tcnt Nanoseconds"
+
+   if [[ $count -ne 0 ]]; then
+      tcnt=$( echo "$tcnt ) / $count" | bc )
+      output="$output\nWrites:,Performed = $count,AvgTime = $tcnt Seconds"
+   fi
+
    tcnt="( 0.0"
    count=0
 
    while read -r line; do
+      line=$( echo "$line" | awk '{print $2}' )
       tcnt="$tcnt + $line"
       count=$(( count + 1 ));
    done < "$TLOGPREF$$.read"
-   tcnt=$( echo "$tcnt ) / $count" | bc )
-   
-   output="$output\nReads:,Performed = $count,AvgTime = $tcnt Nanoseconds"
+
+   if [[ $count -ne 0 ]]; then
+      tcnt=$( echo "$tcnt ) / $count" | bc )
+      output="$output\nReads:,Performed = $count,AvgTime = $tcnt Seconds"
+   fi
+
    tcnt="( 0.0"
    count=0
 
    while read -r line; do
+      line=$( echo "$line" | awk '{print $2}' )
       tcnt="$tcnt + $line"
       count=$(( count + 1 ));
    done < "$TLOGPREF$$.recovery"
-   tcnt=$( echo "$tcnt ) / $count" | bc )
-   
-   output="$output\nRecoveries:,Performed = $count,AvgTime = $tcnt Nanoseconds"
+
+   if [[ $count -ne 0 ]]; then
+      tcnt=$( echo "$tcnt ) / $count" | bc )
+      output="$output\nRecoveries:,Performed = $count,AvgTime = $tcnt Seconds"
+   fi
+
    tcnt="( 0.0"
    count=0
 
    while read -r line; do
+      line=$( echo "$line" | awk '{print $2}' )
       tcnt="$tcnt + $line"
       count=$(( count + 1 ));
    done < "$TLOGPREF$$.status"
-   tcnt=$( echo "$tcnt ) / $count" | bc )
-   
-   output="$output\nStatus:,Performed = $count,AvgTime = $tcnt Nanoseconds"
 
-   printf "$output\n" | column -s "," -o "   " -t
+   if [[ $count -ne 0 ]]; then
+      tcnt=$( echo "$tcnt ) / $count" | bc )
+      output="$output\nStatus:,Performed = $count,AvgTime = $tcnt Seconds"
+   fi
+
+   { res=$( printf "$output\n" | column -s "," -o "   " -t ); } 2>/dev/null
+
+   if [[ $? -ne 0 ]]; then
+      { res=$( printf "$output\n" | column -s "," -c 100 -t ); } 2>/dev/null
+   fi
+
+   echo "$res"
+
    echo
 fi
 
